### ISSUE TITLE
Getting stuck on door frames

### ISSUE THREAD

**Issue by Skaruts** [alexjhetherington/godot-character-controller-example#3] opened 2023-11-03 13:11 UTC
Hi, there. I've been trying out this controller in my project and I'm quite happy about it, it's working great, except for this one thing: sometimes I get stuck on door frames, as in the gif below. I am using Jolt physics, btw.

This seems related to the collision cylinder height, though. The cylinder in the gif below is 1.8 high and my doors are 2 meters high. I tried smaller cylinder sizes, and at 1.6 high I didn't have this issue anymore. 

I recreated my door frames with CSG boxes just to see if they would behave the same as my trenchbroom geometry, and they did. To reproduce it, all I have to do is walk into the door frame and keep pushing W while it slides into the open space. Most of the time it won't enter the open space, like in the gif. 

![fps_controller_door_bug](https://github.com/alexjhetherington/godot-character-controller-example/assets/6277234/610bf0ce-cd50-4935-9324-f9f56eee37a6)

However, I tested this in your demo project and the behavior was a bit different, for some reason (maybe something I changed in mine). Instead of sliding like in the gif above, it gets stuck to the corners of the CSGBoxes. But this still seems related to the collision height, as lowering the cylinder height made it stop getting stuck (and I had no issues at all with the pillar on the right, in the picture below).

![fps_controller_door_bug_2 gif](https://github.com/alexjhetherington/godot-character-controller-example/assets/6277234/e7ca1037-7901-4b74-949a-cd4c015ae8e9)

**Comment by alexjhetherington** [comment] 2023-11-03 13:27
My quick guess is that it's related to the stepping algorithm, if you want to share your demo scene I'm happy to take a look a bit later.

**Comment by Skaruts** [comment] 2023-11-03 13:50
You mean just the scene with the door frame? It's just three CSG boxes (four with the ground). 

[test.zip](https://github.com/alexjhetherington/godot-character-controller-example/files/13250859/test.zip)

If you want a test project I'll have to create a new one to isolate the player and the test scene, because my project is full of stuff. Let me know if you'd prefer that.

**Comment by alexjhetherington** [comment] 2023-11-03 14:31
I can't reproduce it. I perhaps accidentally fixed this already. Make sure you have this commit: https://github.com/alexjhetherington/godot-character-controller-example/commit/f51131cee833eff71838e3e304bf80686af77308

If you already have that and you're still seeing the bug please do create a separate reproduction project if you'd like me to take a look.

(note - I added a doorway to the demo scene)

**Comment by Skaruts** [comment] 2023-11-03 14:58
Hmm, those problems are indeed no longer in the latest demo. The demo I had was the one I had downloaded before the `f51131c` fix. 

What's strange is that I actually added that fix to the controller in my project before I created this issue. Although I added it manually, because the controller in my project already has quite a few changes (jumping, sprinting, sneaking (without crouching), etc). 

I'm going to double-check I didn't goof it, and I'll make a reproduction project.

**Comment by Skaruts** [comment] 2023-11-03 15:17
Actually, it's the `step_height`. If you raise it `0.3` you should be able to reproduce the issue. I'm being able to do that in the latest demo.

I'm using `0.375` in my project, which is even higher.

**Comment by alexjhetherington** [comment] 2023-11-03 15:27
Nice. Will look into it

**Comment by alexjhetherington** [comment] 2023-11-03 16:13
Fixed in this commit.

Issue was that the character controller failed to recognise that there was a valid "non-stepping" movement it could make

https://github.com/alexjhetherington/godot-character-controller-example/commit/0d1c19b1cb5c6856273a6d1cf6c303a0c05711fa

Feel free to reopen or open a new one if any other issues

**Comment by alexjhetherington** [comment] 2023-11-03 17:03
Reopening because I introduced another bug somewhere

**Comment by alexjhetherington** [comment] 2023-11-03 17:25
Closing again because it is fixed and didn't cause any regression. But testing this did lead me to find this: https://github.com/alexjhetherington/godot-character-controller-example/issues/4

**Closed as completed by alexjhetherington** 2023-11-03 17:25 UTC

**Comment by Skaruts** [comment] 2023-11-03 18:29
Thanks. :)
